### ISSUE TITLE
DNS REQUEST: release.triage.k8s.io

### ISSUE THREAD

**Issue by ameukam** [kubernetes/k8s.io#1023]
### Type of DNS update:
Create

### Domain being modified:
e.g. `k8s.io`

### New DNS Record:

```yaml
 release.triage:
- type: A
  value: 35.186.239.70
```

### Reason for update:

DNS entry for triage-party
