### ISSUE TITLE
DNS REQUEST: cluster-api-provider-azure.sigs

### ISSUE THREAD

**Issue by CecileRobertMichon** [kubernetes/k8s.io#1182]
### Type of DNS update:
Create

### Domain being modified:
k8s.io

### New DNS Record:
```yaml
# https://github.com/kubernetes-sigs/cluster-api-provider-azure docs (@CecileRobertMichon, @nader-ziada, @devigned)
cluster-api-provider-azure.sigs:
  type: CNAME
  value: kubernetes-sigs-cluster-api-provider-azure.netlify.app.
  ```
### Reason for update:
The sig-cluster-lifecycle cluster-api-provider-azure subproject has requested a netlify site to host its documentation. ref https://github.com/kubernetes/org/issues/2122#issuecomment-681058974.
