### ISSUE TITLE
DNS REQUEST: kustomize.sigs

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/k8s.io#1396]
### Type of DNS update:
one of: Create

### Domain being modified:
`k8s.io`

### New DNS Record:

```yaml
# https://github.com/kubernetes-sigs/cli-experimental docs (@pwittrock @seans3 @eddiezane @soltysh)
kustomize.sigs:
  type: CNAME
  value: cli-experimental.netlify.app.
```

### Reason for update:

Create DNS entry for kustomize docs.
