### ISSUE TITLE
audit followup: k8s-infra GCP projects shouldn't have random services enabled

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#1887]
This is a followup to https://github.com/kubernetes/k8s.io/issues/1675 which was focused just on k8s-staging-* GCP projects

While I haven't found docs for it, I am told that over-privileged users (e.g. organization admins) who use the UI are capable of auto-enabling services as they click from project-to-project or service-to-service.  I think I often run into this when I'm using a service in my personal project, and then switch to a kubernetes.io project.

https://github.com/kubernetes/k8s.io/pull/1859 adds an `ensure_only_services "${project}" "${services[@]}"` function to auto-disable services that were directly specified, or direct dependencies of what was specified.  I wasn't comfortable enabling it by default for everything, and I didn't want to rewrite ensure-prod-storage.sh just yet.

This issue is intended to cover:
- determining what set of services we think should be enabled by default for a given class/type of project
- determining how to add in special-case services for a given project (e.g. prod-only, test-only)
- pruning services until we're sure we have only what we want enabled
- enabling some mechanism to enforce continually, e.g.
  - remove obnoxiously long env var gate, do it every time ensure_project is run by any human running a script
  - setup a custom script that only prunes services, run a prowjob that does this
  - etc.

**Comment by spiffxp** [comment]
As part of https://github.com/kubernetes/k8s.io/pull/1890 I'm looking at k8s-conform's services.  This project should be storage-only, so definitely going to disable compute
```
k8s-conform:
  intent:
    - secretmanager.googleapis.com
    - storage-api.googleapis.com
    - storage-component.googleapis.com
  enabled:
    - compute.googleapis.com
    - oslogin.googleapis.com
    - secretmanager.googleapis.com
    - storage-api.googleapis.com
    - storage-component.googleapis.com
  expected:
    - secretmanager.googleapis.com
    - storage-api.googleapis.com
    - storage-component.googleapis.com
  to_enable: []
  to_disable:
    - compute.googleapis.com
    - oslogin.googleapis.com
```
