### ISSUE TITLE
Cloud provider ASNs store

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/k8s.io#1914]
I'd like to create a folder in this repo to manage the known ASNs for each CNCF-supported cloud-provider. This will mean for query-able IP blocks that will end up being used with a 302-redirect or split-horizon DNS for {artifacts,registry}.k8s.io.

Examples:
```yaml
#infra/meta/asns/microsoft.yaml
name: microsoft
redirectsTo: 
  registry: kubernetes.acr.io
  artifacts: k8s-artifacts.acr.io
asns:                                                                                                                               
- 12076                                                                                                                           
- 8075                                                                                                                            
- 8068                                                                                                                            
- 8069                                                                                                                            
- 16550
```
```yaml
#infra/meta/asns/google.yaml
name: google
redirectsTo:
  registry: kubernetes.gcr.io
  artifacts: kubernetes-release.storage.googleapis.com                                                                                                                        
asns:                                                                                                                               
- 39190                                                                                                                           
- 139070                                                                                                                          
- 45566                                                                                                                           
- 15169                                                                                                                           
- 19527                                                                                                                           
- 36040                                                                                                                           
- 43515                                                                                                                           
- 16550
```
```yaml
#infra/meta/asns/amazon.yaml
name: amazon
redirectsTo:
  registry: kubernetes.ecr.io
  artifacts: kubernetes.s3.amazon.com
asns:
  - 16509
```
(so forth...)

It would be lovely to also have a representative from each cloud-provider to :ballot_box_with_check: verify these ASNs represent their networks.
