### ISSUE TITLE
cip-auditor: alerts are noisy

### ISSUE THREAD

**Issue by spiffxp** [kubernetes/k8s.io#2364]
Tracking issue for the fact that CIP auditor alerts are noisy.

The alerting was manually created by thockin a while ago (could not find an issue to link at a glance, maybe someone else knows).  Then it was manually disabled because the alerts were perceived as noisy.

The alerting is managed via click-ops, ideally it could be done with `gcloud`: https://github.com/kubernetes/k8s.io/issues/1624

IAM policies to allow viewing of incidents and alerts without granting admin access to k8s-artifacts prod would be helpful.  What's the appropriate group to grant this access to?

/cc @listx 
FYI @tylerferrara 
Making this tracking issue since I'm about to make a manual IAM change and I want to document it somewhere

**Comment by spiffxp** [comment]
FWIW here is the policy generating the alert in question
```yaml
# $ gcloud alpha monitoring policies list --project=kubernetes-public
---
combiner: OR
conditions:
- conditionThreshold:
    aggregations:
    - alignmentPeriod: 60s
      crossSeriesReducer: REDUCE_MAX
      perSeriesAligner: ALIGN_RATE
    comparison: COMPARISON_GT
    duration: 0s
    filter: metric.type="logging.googleapis.com/user/cip-auditor-alert"
    trigger:
      count: 1
  displayName: logging/user/cip-auditor-alert
  name: projects/kubernetes-public/alertPolicies/12089518252001301876/conditions/12089518252001300531
creationRecord:
  mutateTime: '2020-03-31T00:27:12.391234443Z'
  mutatedBy: thockin@REDACTED
displayName: Image promoter alert
documentation:
  content: The image promoter has logged something that we consider an alert.
  mimeType: text/markdown
enabled: true
mutationRecord:
  mutateTime: '2020-03-31T01:45:19.410085124Z'
  mutatedBy: thockin@REDACTED
name: projects/kubernetes-public/alertPolicies/12089518252001301876
notificationChannels:
- projects/kubernetes-public/notificationChannels/7630148271419930225
- projects/kubernetes-public/notificationChannels/17367851054639804370
- projects/kubernetes-public/notificationChannels/2533614711603005061
- projects/kubernetes-public/notificationChannels/7846745591716920888
```
