### ISSUE TITLE
DNS REQUEST: cluster-api-openstack.sigs.k8s.io

### ISSUE THREAD

**Issue by tobiasgiese** [kubernetes/k8s.io#2492]
### Type of DNS update:
Create

### Domain being modified:
`k8s.io`

### New DNS Record:

```yaml
# https://github.com/kubernetes-sigs/cluster-api-provider-openstack/ (@jichenjc @sbueringer @hidekazuna)
cluster-api-openstack.sigs:
- type: CNAME
  value: kubernetes-sigs-cluster-api-openstack.netlify.com
```

### Reason for update:

Part of https://github.com/kubernetes/org/issues/2883

<sub>Tobias Giese <tobias.giese@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>
