### ISSUE TITLE
DNS REQUEST: cli.triage.k8s.io

### ISSUE THREAD

**Issue by eddiezane** [kubernetes/k8s.io#2621]
### Type of DNS update:
Create

### Domain being modified:
`k8s.io`

### New DNS Record:

```yaml
cli.triage:
- type: A
  value: 34.117.106.163
```

### Reason for update:

Ref: https://github.com/kubernetes/k8s.io/issues/2460

/assign @ameukam

I'm not sure what this will point to yet. LB from the service or and ingress controller?
