### ISSUE TITLE
DNS REQUEST: relnotes.k8s.io

### ISSUE THREAD

**Issue by jeefy** [kubernetes/k8s.io#270]
### Type of DNS update:
Create

### Domain being modified:
k8s.io

### New DNS Record:
```yaml
# https://github.com/kubernetes-sigs/release-notes
relnotes:
  type: CNAME
  value: kubernetes-sigs-relnotes.netlify.com
  ```
### Reason for update:
Creation of a user-facing release notes website. As this will be linked to and distributed for future releases, a shorter URL would be preferred and thus should not fall under the `sigs` subdomain.

Relevant [KEP](https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/20190331-release-notes.md)

cc @spiffxp @justaugustus @onyiny-ang
