### ISSUE TITLE
DNS REQUEST: minikube.sigs.k8s.io

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/k8s.io#284]
### Type of DNS update:
Create

### Domain being modified:
k8s.io

### New DNS Record:

```yaml
# https://github.com/kubernetes-sigs/minikube (tstromberg@ afbjorklund@)
minikube.sigs:
  type: CNAME
  value: kubernetes-sigs-minikube.netlify.com
```

### Reason for update:

To support the new minikube docs site, as requested here: https://github.com/kubernetes/org/issues/855#issuecomment-498023303
