### ISSUE TITLE
CoCC vanity urls request

### ISSUE THREAD

**Issue by tpepper** [kubernetes/k8s.io#2923]
### Type of DNS update:
Create

### Domain being modified:
k8s.io

### New DNS Record:

```yaml
transparency:
- type: CNAME
  value: redirect.k8s.io.
conduct:
- type: CNAME
  value: redirect.k8s.io.
```

### Reason for update:

Code of Conduct Committee proposes two vanity short url redirects:

 * transparency.k8s.io to https://github.com/kubernetes/community/tree/master/committee-code-of-conduct/transparency-reports
* conduct.k8s.io to https://github.com/kubernetes/community/tree/master/committee-code-of-conduct
