### ISSUE TITLE
DNS REQUEST: k8s-prow.netlify.app

### ISSUE THREAD

**Issue by listx** [kubernetes/k8s.io#3315]
### Type of DNS update:
Create

### Domain being modified:
`k8s.io`

### New DNS Record:
```yaml
# https://github.com/kubernetes-sigs/prow docs (@alvaroaleman, @cblecker, @cjwagner, @fejta, @stevekuznetsov, @petr-muller)
docs.prow:
  type: CNAME
  value: k8s-prow.netlify.app
  ```
### Reason for update:
The Prow subproject has requested a netlify site to host its documentation. ref [netlify site request](https://github.com/kubernetes/org/issues/3177), [umbrella issue](https://github.com/kubernetes/test-infra/issues/24821)
