### ISSUE TITLE
DNS REQUEST: cloud-provider-azure.sigs.k8s.io

### ISSUE THREAD

**Issue by MartinForReal** [kubernetes/k8s.io#3840]
### Type of DNS update:
Create
### Domain being modified:
k8s.io
### New DNS Record:

```yaml
cloud-provider-azure.sigs:
- type: CNAME
  value: kubernetes-sigs-cloud-provide-azure.netlify.app
```

### Reason for update:

The cloud proviider azure subproject has requested a netlify site to host its documentation via https://github.com/kubernetes/org/issues/3268?notification_referrer_id=NT_kwDOAE91trIzMTI0MjY5NzcyOjUyMDc0Nzg#issuecomment-1155121919
