### ISSUE TITLE
DNS REQUEST: kops.sigs.k8s.io

### ISSUE THREAD

**Issue by mikesplain** [kubernetes/k8s.io#430]
### Type of DNS update:
Create

### Domain being modified:
k8s.io

### New DNS Record:

```yaml
# https://github.com/kubernetes/kops (@mikesplain @justinsb)
kops.sigs:
  type: CNAME
  value: kubernetes-kops.netlify.com
```
### Reason for update:

To support new kops netlify site: https://github.com/kubernetes/org/issues/1342
