### ISSUE TITLE
RBAC role for users - are these resources enough?

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#442]
As we discussed in last few zoom calls I was working on creating the role (RBAC) for the users.

After some conversation with @thockin this is the result of my work:
```
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: namespace-user
  namespace: {{namespace}}
rules:
- apiGroups: [""]
  resources: ["configmaps", "endpoints", "persistentvolumeclaims", "pods", "resourcequotas", "services"]
  verbs: ["*"]
- apiGroups: ["certmanager.k8s.io"]
  resources: ["certificates"]
  verbs: ["*"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["extensions"]
  resources: ["deployments", "ingresses", "networkpolicies"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["list"]
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["list"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings", "clusterroles", "rolebindings", "roles"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: bart-testing-namespace-user-binding
  namespace: bart-testing
subjects:
- kind: Group
  name: k8s-infra-rbac-{{namespace}}@kubernetes.io
  namespace: {{namespace}}
roleRef:
  kind: Role
  name: namespace-user
  apiGroup: rbac.authorization.k8s.io
```
This issue was created to ask you if these resources will be enough?

Bart

**Comment by thockin** [comment]
Typo:

```
rules:
- apiGroups: [""]
  resources: ["configmaps", "endpoints", "events", "persistentvolumeclaims", "pods", "resourcequotas", "services"]
  verbs: ["*"]a
```
Errant "a"

I don't think we need to be able to write events, just list and read.

We should only use apps/deployment

I don't think we need projectcalico networkpolicies

storageclasses list is OK

priorityclasses list is OK

I expect we'll want namespaces list at some point and maybe nodes list, but let's try without those.
