### ISSUE TITLE
DNS REQUEST: kmm.sigs.k8s.io

### ISSUE THREAD

**Issue by iranzo** [kubernetes/k8s.io#4471]
### Type of DNS update:
Create

### Domain being modified:

k8s.io

### New DNS Record:

```yaml
kmm.sigs.k8s.io:
- type: CNAME
  value: kubernetes-sigs-kmm.netlify.app
```

### Reason for update:

Request for Netlify domain at https://github.com/kubernetes/org/issues/3839
