### ISSUE TITLE
DNS REQUEST: kwok.sigs.k8s.io

### ISSUE THREAD

**Issue by wzshiming** [kubernetes/k8s.io#4581]
### Type of DNS update:
one of: Create, Delete, Update

### Domain being modified:
`kwok.sigs.k8s.io`

### New DNS Record:

```yaml
# https://github.com/kubernetes-sigs/kwok docs (@wzshiming, @yibozhuang, @Huang-Wei)
kwok.sigs:
  type: CNAME
  value: k8s-kwok.netlify.app.
```
