### ISSUE TITLE
DNS Update Request

### ISSUE THREAD

**Issue by justinsb** [kubernetes/k8s.io#4708]
### Type of DNS update:
Create

### Domain being modified:
`k8s.io`

### New DNS Record:

```yaml
# Sandbox artifact redirector service.
artifacts-sandbox:
  - type: A
    value: 34.110.218.166
  - type: AAAA
    value: "2600:1901:0:3b54::"
```

### Reason for update:

Creating artifacts-sandbox.k8s.io pointing to load balancer IP addresses in k8s-infra-porche-sandbox
