### ISSUE TITLE
Mutate `eks-prow-build-cluster` image pulls to use ECR

### ISSUE THREAD

**Issue by upodroid** [kubernetes/k8s.io#4928]
Can we look in to using Kyverno to mutate image pulls on the eks-prow-build-cluster?

It will be faster and cheaper to pull images from ECR than the staging GCR registries.

Good candidates for sync to ECR would would be
- `gcr.io/k8s-prow/*` 
- `gcr.io/k8s-staging-test-infra/*`
- `gcr.io/k8s-staging-*/*`

Kyverno would rewrite the image that the submitted from `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20230222-b5208facd4-master` to `ACCOUNT_NUMBER.dkr.ecr.us-east-2.amazonaws.com/[REPO_NAME]/kubekins-e2e:v20230222-b5208facd4-master`

We would also have a prowjob that syncs that ECR repo with images from the staging repos.

Sample Kyverno policy:
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: kubernetes-gcr-to-registry    
spec:
  background: false
  rules:
    - name: replace-image-registry-pod-containers
      match:
        any:
        - resources:
            kinds:
            - Pod
      mutate:
        foreach:
        - list: "request.object.spec.containers"
          patchStrategicMerge:
            spec:
              containers:
              - name: "{{ element.name }}"
                image: "{{ replace_all('{{element.image}}', 'k8s.gcr.io', 'registry.k8s.io' )}}"
    - name: replace-image-registry-pod-initcontainers
      match:
        any:
        - resources:
            kinds:
            - Pod
      preconditions:
        all:
        - key: "{{ request.object.spec.initContainers[] || `[]` | length(@) }}"
          operator: GreaterThanOrEquals
          value: 1
      mutate:
        foreach:
        - list: "request.object.spec.initContainers"
          patchStrategicMerge:
            spec:
              initContainers:
              - name: "{{ element.name }}"
                image: "{{ replace_all('{{element.image}}', 'k8s.gcr.io', 'registry.k8s.io' )}}"
```

/cc @ameukam @xmudrii
