### ISSUE TITLE
DNS REQUEST: mutlicluster.sigs.k8s.io

### ISSUE THREAD

**Issue by jmhbnz** [kubernetes/k8s.io#4991]
### Type of DNS update:
Create

### Domain being modified:
`multicluster.sigs.k8s.io`

### New DNS Record:

```yaml
www:
- type: CNAME
  value: kubernetes-sig-multicluster.netlify.app
```

### Reason for update:

Required for new sig-multicluster docs netlify site.
