### ISSUE TITLE
DNS REQUEST: `packages.k8s.io` and `packages.kubernetes.io`

### ISSUE THREAD

**Issue by xmudrii** [kubernetes/k8s.io#5517]
### Type of DNS update:

Create

### Domain being modified:

`packages.k8s.io` and `packages.kubernetes.io`

### Existing DNS Record:

None

### New DNS Record:

```yaml
packages:
  type: CNAME
  value: redirect.k8s.io.
```

### Reason for update:

Implementing URLs for OpenBuildService as part of https://github.com/kubernetes/enhancements/issues/1731
