### ISSUE TITLE
DNS REQUEST: scheduler-plugins.sigs.k8s.io

### ISSUE THREAD

**Issue by zwpaper** [kubernetes/k8s.io#5774]
### Type of DNS update:
Create

### Domain being modified:
scheduler-plugins.sigs.k8s.io

### New DNS Record:

```yaml
scheduler-plugins.sigs:
- type: CNAME
  value: kubernetes-sigs-scheduler-plugins.netlify.app.
```

### Reason for update:

Create a docs site for scheduler plugins https://github.com/kubernetes-sigs/scheduler-plugins
