### ISSUE TITLE
DNS REQUEST: krew.sigs.k8s.io

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/k8s.io#614]
### Type of DNS update:

Create

### Domain being modified:

`k8s.io`

### New DNS Record:

```yaml
# https://github.com/kubernetes-sigs/krew docs (@ahmetb, @corneliusweig)
krew.sigs:
- type: CNAME
  value: kubernetes-sigs-krew.netlify.com.
```

### Reason for update:

New sub-project site for [Krew](https://sigs.k8s.io/krew): https://github.com/kubernetes/org/issues/1668.
