### ISSUE TITLE
DNS REQUEST: <your-dns-record>

### ISSUE THREAD

**Issue by redlaminoe** [kubernetes/k8s.io#6344]
### Type of DNS update:
one of: Create, Delete, Update

### Domain being modified:
e.g. `k8s.io`

### Existing DNS Record:

```yaml
# this is the sub-domain, '' for the top-level domain
www:
# this is the record type, e.g A, CNAME, MX, TXT, etc.
- type: A
  # This depends on the record type, see existing YAML files for more examples.
  value: 35.201.71.162
```

### New DNS Record:

```yaml
www:
- type: CNAME
  value: some.other.host.com
```

### Reason for update:

Example of an update.
