### ISSUE TITLE
DNS REQUEST: dash.etcd.io

### ISSUE THREAD

**Issue by jmhbnz** [kubernetes/k8s.io#6604]
### Type of DNS update:
Delete

### Domain being modified:
`etcd.io`

### Existing DNS Record:

```yaml
dash:
  - type: A
    value: 104.198.97.34
```

### Reason for update:

This dns record is no longer required, the `dash.etcd.io` service was retired in 2018, refer https://github.com/etcd-io/etcd/issues/10073,
