### ISSUE TITLE
DNS REQUEST: perf-dash-canary.k8s.io

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#732]
### Type of DNS update:
Create

### Domain being modified:
`k8s.io`

### New DNS Record:

```yaml
perf-dash-canary:
- type: A
  value: 34.102.200.94
```

### Reason for update:
We created static IP address called: `perf-dash-k8s-io-ingress-prod` for perf-dash's Ingress, this subdomain will be usied to perform final test for perf-dash deployment when `https://github.com/kubernetes/k8s.io/pull/721` will be closed
