### ISSUE TITLE
DNS REQUEST: perf-dash.k8s.io

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#772]
### Type of DNS update:
Update

### Domain being modified:
`k8s.io`

### Existing DNS Record:

```yaml
perf-dash:
  type: A
  value: 35.188.102.189
```

### New DNS Record:

```yaml
perf-dash:
  type: A
  value: 34.102.200.94
```

### Reason for update:
As we have confitrmation all issues with accessing our cluster namespaces for members of rbac groups were resolved and  that the data between [perf-dash.k8s.io](https://perf-dash.k8s.io) and [perf-dash-canary.k8s.io](https://perf-dash-canary.k8s.io) are consistent we can switch the DNS record of `perf-dash.k8s.io` to point to the new place (inside the `aaa` cluster)

/cc @mm4tt @wojtek-t @BenTheElder
