### ISSUE TITLE
DNS REQUEST: perf-dash-canary.k8s.io

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#776]
### Type of DNS update:
Delete

### Domain being modified:
`k8s.io`

### Existing DNS Record:

```yaml
perf-dash-canary:
  type: A
  value: 34.102.200.94
```

### Reason for update:

As #773 was merged and DNSes reconcilled perf-dash.k8s.io now points to the `aaa` cluster and the perf-dash-canary.k8s.io after confirmation from @mm4tt or @wojtek-t everything works as expected will be unnecessary, I don't see the need of having this record still present.

/cc @mm4tt @wojtek-t @BenTheElder
