### ISSUE TITLE
DNS REQUEST: slack-staging.kubernetes.io

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#796]
### Type of DNS update:
Create

### Domain being modified:
`kubernetes.io`

### New DNS Record:

```yaml
slack-staging:
  type: A
  value: 34.102.202.147
```

### Reason for update:

As we are in the process of moving slack-infra tools to our new infrastructure this record will use us to test everything works as expected before we'll switch proper domains (slack.k8s.io to the new place)
