### ISSUE TITLE
DNS REQUEST: capz-monitoring.sigs.k8s.io

### ISSUE THREAD

**Issue by willie-yao** [kubernetes/k8s.io#7978]
### Type of DNS update:
Create

### Domain being modified:
k8s.io

### New DNS Record:

```yaml
# https://github.com/kubernetes-sigs/cluster-api-provider-azure monitoring (@willie-yao @nawazkh @jackfrancis)
capz-monitoring.sigs:
  type: CNAME
  value: capz-monitoring.netlify.app.
```

### Reason for update:
The sig-cluster-lifecycle cluster-api-provider-azure subproject has requested a netlify site to host a grafana dashboard for monitoring performance metrics on CAPZ. ref: [#5524](https://github.com/kubernetes/org/issues/5524)
