### ISSUE TITLE
DNS REQUEST: container-object-storage-interface.sigs.k8s.io

### ISSUE THREAD

**Issue by shanduur** [kubernetes/k8s.io#8124]
### Type of DNS update:
Create

### Domain being modified:
`k8s.io`

### New DNS Record:

```yaml
container-object-storage-interface.sigs:
- type: CNAME
  value: container-object-storage-interface.netlify.app
```

### Reason for update:

The container-object-storage-interface subproject has requested a netlify site to host its documentation via https://github.com/kubernetes/org/issues/5611

**Comment by BenTheElder** [comment]
We should probably have the project live first.
Once that is live this is a small PR to the DNS config in this repo.

**Comment by reylejano** [comment]
@shanduur , 
kubernetes-sigs-container-object-storage-interface is too long for a netlify project, how about container-object-storage-interface. 
This follows existing netlify projects like cluster-api, image-builder, and more

The request will be:

```yaml
container-object-storage-interface.sigs:
- type: CNAME
  value: container-object-storage-interface.netlify.app
```
The site url will be `https://container-object-storage-interface.sigs.k8s.io`
