### ISSUE TITLE
DNS REQUEST: slack.kubernetes.io

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#815]
### Type of DNS update:
Update

### Domain being modified:
`kubernetes.io`

### Existing DNS Record:

```yaml
slack:
  type: A
  value: 130.211.42.98
```

### New DNS Record:

```yaml
slack:
  type: A
  value: 34.107.195.71
```

### Reason for update:

As we discussed with at slack's channel [#slack-admins](https://kubernetes.slack.com/archives/C4M06S5HS/p1587979163078600) the plan is to switch dns records to point to the same place as [slack-staging.k8s.io](https://slack-staging.k8s.io) and test if `slack-event-log`, `slack-moderator` and `slack-welcomer` works as expected. If anything goes wrong, we'll rollback the old records.

@munnerz will be helping me as he is a slack-admin :-)
