### ISSUE TITLE
DNS REQUEST: slack-staging.k8s.io

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#816]
### Type of DNS update:
Delete

### Domain being modified:
e.g. `k8s.io`

### Existing DNS Record:

```yaml
slack-staging:
  type: A
  value: 34.107.195.71
```

### Reason for update:

When we'll switch [slack.k8s.io](https://slack.k8s.io) and [slack.kubernetes.io](https://slack.kubernetes.io) to point to the `aaa` and we'll test everything works as expected, we''ll want to get rid of this unnecessary subdomain.

ref. #814, #815
/cc @munnerz
