### ISSUE TITLE
DNS REQUEST: node-perf-dash-staging.k8s.io

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#869]
### Type of DNS update:
Create

### Domain being modified:
`k8s.io`

### Existing DNS Record:

None

### New DNS Record:

```yaml
node-perf-dash-staging:
  type: A
  value: 35.227.254.215
```

### Reason for update:

Temporary/staging domain in the process of moving `node-perf-dash` to the `aaa` cluster (ref. [#864#issuecomment-628601730](https://github.com/kubernetes/k8s.io/pull/864#issuecomment-628601730))

cc. @lorqor
