### ISSUE TITLE
Automate Static IPs creation

### ISSUE THREAD

**Issue by bartsmykla** [kubernetes/k8s.io#872]
When I was running the [`infra/gcp/ensure-static-ips.sh`](https://github.com/kubernetes/k8s.io/blob/34ea4fee9e0c47bf17730bc9878cc57acf50ef0c/infra/gcp/ensure-main-project.sh) I came to realization it's the great thing to automate.

Steps I want to follow:

1. Waiting for #871 to be merged

2. Creating a PR and updating [`infra/gcp/ensure-main-project.sh`](https://github.com/kubernetes/k8s.io/blob/34ea4fee9e0c47bf17730bc9878cc57acf50ef0c/infra/gcp/ensure-main-project.sh):

   ```shell
   readonly ADDRESS_CREATOR_SVCACCT="k8s-infra-address-creator"
   readonly ADDRESS_CREATOR_SVCACCT_EMAIL="$(svc_acct_email "${PROJECT}" \
      "${ADDRESS_CREATOR_SVCACCT}")"

   color 6 "Ensuring the ${ADDRESS_CREATOR_SVCACCT} serviceaccount exists"
   ensure_service_account \
      "${PROJECT}" \
      "${ADDRESS_CREATOR_SVCACCT}" \
      "Grants permissions to get and create compute addresses"

   color 6 "Ensuring the ComputeAddressCreator IAM role exists"
   ensure_custom_iam_role "${PROJECT}" \
      ComputeAddressCreator \
      "Compute Address Creator" \
      "Can get and create compute addresses" \
            compute.addresses.get \
            compute.addresses.create

   color 6 "Binding the ComputeAddressCreator IAM role to the \
      ${ADDRESS_CREATOR_SVCACCT} service account"
   gcloud projects add-iam-policy-binding "${PROJECT}" \
      --member "serviceAccount:${ADDRESS_CREATOR_SVCACCT_EMAIL}" \
      --role "projects/${PROJECT}/roles/ComputeAddressCreator"

   color 6 "Empowering ${ADDRESS_CREATOR_SVCACCT} serviceaccount to be used \
      on build cluster"
   empower_ksa_to_svcacct \
      "kubernetes-public.svc.id.goog[test-pods/${ADDRESS_CREATOR_SVCACCT}]" \
      "${PROJECT}" \
      "${ADDRESS_CREATOR_SVCACCT_EMAIL}"
   ```

3. Waiting for [someone with permissions](https://github.com/kubernetes/k8s.io/blob/master/groups/groups.yaml#L281-L292) to run the [`infra/gcp/ensure-main-project.sh`](https://github.com/kubernetes/k8s.io/blob/34ea4fee9e0c47bf17730bc9878cc57acf50ef0c/infra/gcp/ensure-main-project.sh)

4. Creating a PR at k/test-infra with:

   - Update of the [`k/test-infra/config/prow/cluster/trusted_serviceaccounts.yaml`](https://github.com/kubernetes/test-infra/blob/bc6a077f2ca569a84fdca22807021c419165212e/config/prow/cluster/trusted_serviceaccounts.yaml) file by adding:

      ```yaml
      ---
      kind: ServiceAccount
      apiVersion: v1
      metadata:
      annotations:
      iam.gke.io/gcp-service-account: k8s-infra-address-creator@kubernetes-public.iam.gserviceaccount.com
      name: k8s-infra-address-creator
      namespace: test-pods
      ```

   - New postsubmit job at [`k/test-infra/config/jobs/kubernetes/wg-k8s-infra`](https://github.com/kubernetes/test-infra/blob/bc6a077f2ca569a84fdca22807021c419165212e/config/jobs/kubernetes/wg-k8s-infra):

      ```yaml
      postsubmits:
         kubernetes/k8s.io:
         - name: k8sio-ensure-addresses
            annotations:
               testgrid-dashboards: wg-k8s-infra-k8sio
               testgrid-alert-email: k8s-infra-alerts@kubernetes.io
               testgrid-num-failures-to-alert: '1'
            decorate: true
            run_if_changed: "^infra/gcp/ensure-static-ips.sh$"
            max_concurrency: 1
            branches:
            - ^master$
            spec:
               serviceAccountName: k8s-infra-address-creator
               containers:
               - image: google/cloud-sdk:292.0.0-alpine
               command:
               - ./infra/gcp/ensure-static-ips.sh
      ```
