### ISSUE TITLE
DNS REQUEST: prow-staging.k8s.io

### ISSUE THREAD

**Issue by chizhg** [kubernetes/k8s.io#969]
### Type of DNS update:
Create

### Domain being modified:
`k8s.io`

### Existing DNS Record:
None

### New DNS Record:

```yaml
prow-staging:
- type: A
  value: 34.120.184.174
```

### Reason for update:

Setting up a Prow staging cluster for validating the new images, before rolling out them to the production Prow, based on the [design doc](https://docs.google.com/document/d/1_TdObxHL084WJbjIj83dg6-URV5wm8Oxdu-yk2WnaGY/edit?ts=5eb9b8e5#)

/cc @fejta @cjwagner
